# Generated by Django 3.0 on 2020-04-16 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('s_adminapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StateModel',
            fields=[
                ('State_no', models.AutoField(primary_key=True, serialize=False)),
                ('State_Name', models.CharField(max_length=30, unique=True)),
            ],
        ),
    ]
