# Generated by Django 3.0 on 2020-04-17 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('s_adminapp', '0003_areamodel_citymodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Type_of_resModel',
            fields=[
                ('Type_No', models.AutoField(primary_key=True, serialize=False)),
                ('Type_Of_Place', models.CharField(max_length=40)),
            ],
        ),
    ]
