# Generated by Django 3.0 on 2020-05-14 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('s_adminapp', '0004_type_of_resmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserregisterModel',
            fields=[
                ('Email', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('Password', models.IntegerField()),
            ],
        ),
    ]
