# Generated by Django 3.0 on 2020-05-16 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('s_adminapp', '0005_userregistermodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='orderFoodModel',
            fields=[
                ('F_id', models.AutoField(primary_key=True, serialize=False)),
                ('F_name', models.CharField(max_length=30)),
                ('F_price', models.IntegerField()),
                ('F_image', models.ImageField(upload_to='orders/')),
                ('F_type', models.IntegerField()),
            ],
        ),
    ]
