# Generated by Django 3.0 on 2020-05-16 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('s_adminapp', '0006_orderfoodmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderfoodmodel',
            name='F_price',
            field=models.FloatField(),
        ),
    ]
