# Generated by Django 3.0 on 2020-05-16 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('s_adminapp', '0007_auto_20200516_1006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderfoodmodel',
            name='F_type',
            field=models.CharField(max_length=30),
        ),
    ]
