# Generated by Django 3.0 on 2020-07-16 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('s_adminapp', '0008_auto_20200516_1008'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('Email', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('Password', models.IntegerField()),
                ('Name', models.CharField(default=None, max_length=30)),
                ('Age', models.IntegerField(default=None)),
                ('Phone', models.IntegerField(default=None)),
                ('Gender', models.CharField(default=None, max_length=7)),
                ('Door_No', models.CharField(default=None, max_length=7)),
                ('Street', models.CharField(default=None, max_length=30)),
                ('Area_Or_Village', models.CharField(default=None, max_length=30)),
                ('City', models.CharField(default=None, max_length=30)),
            ],
        ),
        migrations.DeleteModel(
            name='UserregisterModel',
        ),
    ]
