# Generated by Django 3.0 on 2020-04-17 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('s_adminapp', '0004_type_of_resmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='RestarentModel',
            fields=[
                ('Restaurant_Id', models.AutoField(primary_key=True, serialize=False)),
                ('Restaurant_Name', models.CharField(max_length=40, unique=True)),
                ('Restaurant_Email', models.EmailField(max_length=254, unique=True)),
                ('Restaurant_Contact_No', models.IntegerField(unique=True)),
                ('Restaurant_Password', models.IntegerField()),
                ('Restaurant_Otp', models.IntegerField()),
                ('Restaurant_Status', models.CharField(max_length=20)),
                ('Restaurant_Area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='s_adminapp.AreaModel')),
                ('Restaurant_Type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='s_adminapp.Type_of_resModel')),
            ],
        ),
    ]
