# Generated by Django 3.0 on 2020-05-04 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restarent', '0002_food_model_type_of_foodmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food_model',
            name='Food_Image',
            field=models.ImageField(unique=True, upload_to='foods/'),
        ),
    ]
