# Generated by Django 3.0 on 2020-07-16 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restarent', '0003_auto_20200504_1528'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Profile_Image', models.ImageField(upload_to='profiles/')),
            ],
        ),
    ]
