# Generated by Django 3.0 on 2020-07-17 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restarent', '0005_profileseiion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileseiion',
            name='image',
            field=models.FileField(upload_to=''),
        ),
    ]
