# Generated by Django 3.0 on 2020-07-26 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restarent', '0007_auto_20200725_1203'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilemodel',
            name='id',
        ),
        migrations.AddField(
            model_name='profilemodel',
            name='profile',
            field=models.CharField(default=True, max_length=2, primary_key=True, serialize=False),
        ),
    ]
