# Generated by Django 3.0 on 2020-08-02 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restarent', '0009_auto_20200802_1117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food_model',
            name='Food_price',
            field=models.CharField(blank=True, default=None, max_length=10, null=True),
        ),
    ]
