# Generated by Django 3.0 on 2020-08-02 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restarent', '0010_auto_20200802_1135'),
    ]

    operations = [
        migrations.AddField(
            model_name='food_model',
            name='Food_id',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
