# Generated by Django 3.0 on 2020-08-04 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restarent', '0011_food_model_food_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckoutModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
                ('Email', models.EmailField(max_length=254)),
                ('Address', models.CharField(max_length=200)),
                ('City', models.CharField(max_length=50)),
                ('State', models.CharField(max_length=50)),
                ('Zipcode', models.CharField(max_length=50)),
                ('Country', models.CharField(max_length=50)),
            ],
        ),
    ]
