# Generated by Django 3.0 on 2020-08-04 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restarent', '0012_checkoutmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='food_model',
            name='Food_Description',
            field=models.CharField(blank=True, default=None, max_length=1000, null=True),
        ),
    ]
