# Generated by Django 3.0 on 2020-08-16 05:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('s_adminapp', '0009_auto_20200716_1008'),
        ('restarent', '0014_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commentmodel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(max_length=350)),
                ('image', models.ImageField(upload_to='comment_images/')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restarent.UserProfileSessionModel')),
            ],
        ),
        migrations.CreateModel(
            name='Replymodel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reply', models.TextField(max_length=350)),
                ('image', models.ImageField(upload_to='reply_images/')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='s_adminapp.Adminmodel')),
                ('comment_by_user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='restarent.Commentmodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restarent.UserProfileSessionModel')),
            ],
        ),
        migrations.DeleteModel(
            name='comment',
        ),
    ]
